version: "2"

services:
  psdocker:
    image: "postgres"
    #container-name: psdocker
    networks: 
      - kafkanet
    ports:
      - 5432:5432
    #volumes-from: 
    #   - PostgresData  
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "labdef"
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks: 
      - kafkanet
    ports:
      - 2182:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks: 
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"
  consumerservice:
    image: "footballer-team-statistic/message-consumer"
    container_name: messageconsumer
    depends_on:
      - psdocker
    networks: 
      - kafkanet
    ports:
      - 9001:9001
    environment:
      DATABASE_HOST: psdocker
      DATABASE_NAME: labdef
      DATABASE_PORT: 5432
    cpuset: "1"
  eurekaserver:
    image: "footballer-team-statistic/eureka-server:latest"
    container_name: eurekaserver
    hostname: eurekaserver
    depends_on:
      - psdocker
    networks:
      - kafkanet
    ports:
      - 8761:8761
    environment:
      - DATABASE_HOST=psdocker
      - DATABASE_NAME=labdef
      - DATABASE_PORT=5432
      - HOST_NAME=eurekaserver
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
  configserver:
    image: "footballer-team-statistic/config-server:latest"
    container_name: configserver
    hostname: configserver
    depends_on: 
      - eurekaserver
    networks: 
      - kafkanet
    ports:
      - 8085:8085
    links:
      - eurekaserver
    cpuset: "1"
    environment:
      - HOST_NAME=configserver
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
  tfcservice:
    image: "footballer-team-statistic/tfccrud1:latest"
    container_name: tfcservice
    depends_on:
      - eurekaserver
    networks: 
      - kafkanet
    ports:
      - 8100:8100
    links:
      - eurekaserver
      - kafkaserver
    environment:
      - DATABASE_HOST=psdocker
      - DATABASE_NAME=labdef
      - DATABASE_PORT=5432
      - HOST_NAME=eurekaserver
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
  clientservice:
    image: "footballer-team-statistic/client:latest"
    container_name: clientservice
    depends_on:
      - eurekaserver
    networks: 
      - kafkanet
    ports:
      - 8080:8080
    links: 
      - eurekaserver
    environment:
      - HOST_NAME=eurekaserver
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
  gateway:
    build: ./gateway
    environment:
      - HOST_NAME=gateway
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    ports:
      - "8090:8090"
    networks:
      - kafkanet
    depends_on:
      - eurekaserver

networks: 
  kafkanet:
    driver:
      bridge