spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "kafkaserver:9092"

server:
  port: 8090

zuul:
  routes:
    footballer-team-server:
      path: "/**/footballer-team-server**"
      strip-prefix: false
    teamstat-client:
      path: "/teamstat-client**"
      strip-prefix: false

eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]