spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/petroLubchenko/football-stat-config-reposity'
          clone-on-start: true
          search-paths: '/config'
        native:
          search-locations: D:/Admin/Documents/football-stat-config-reposity/config
    stream:
      kafka:
        binder:
          brokers: kafkaserver:9092
          auto-create-topics: true
  profiles:
    active: git



eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 20
    initial-instance-info-replication-interval-seconds: 20
    service-url:
      default-zone: 'http://eurekaserver:8761/eureka/'
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 40

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh